# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ivey-longurl}
  s.version = "0.1.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Fabien Jakimowicz", "Michael D. Ivey"]
  s.date = %q{2010-05-12}
  s.default_executable = %q{longurl}
  s.description = %q{LongURL expands short urls (tinyurl, is.gd, ...) to original ones, using on LongURL.org, internal resolution or direct resolution}
  s.email = %q{ivey@gweezlebur.com}
  s.executables = ["longurl"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "Manifest",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION.yml",
     "bin/longurl",
     "lib/longurl.rb",
     "lib/longurl/constants.rb",
     "lib/longurl/direct.rb",
     "lib/longurl/exceptions.rb",
     "lib/longurl/expand.rb",
     "lib/longurl/expander.rb",
     "lib/longurl/service.rb",
     "lib/longurl/url.rb",
     "longurl.gemspec",
     "test/cache_mock.rb",
     "test/constants.rb",
     "test/expander_test.rb",
     "test/service/no_cache_service_test.rb",
     "test/service/service_cache_test.rb",
     "test/service/service_test.rb",
     "test/service/supported_services_test.rb",
     "test/url_test.rb"
  ]
  s.homepage = %q{http://github.com/ivey/longurl}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{longurl}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{LongURL expands shorten urls (tinyurl, is.gd, ...)}
  s.test_files = [
    "test/cache_mock.rb",
     "test/constants.rb",
     "test/expander_test.rb",
     "test/service/no_cache_service_test.rb",
     "test/service/service_cache_test.rb",
     "test/service/service_test.rb",
     "test/service/supported_services_test.rb",
     "test/url_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
  end
end

